from .prompt_gen.prompt_list import MpiPromptList
from .prompt_gen.prompt_list_selector import MpiPromptListSelector
from .prompt_gen.prompt_processor import MpiPromptProcessor
from .prompt_gen.prompt_chain_selector import MpiPromptChainSelector
from .prompt_gen.prompt_list_join import MpiPromptListJoin
from .prompt_gen.has_options import MpiHasOptions
from .prompt_gen.prompt_bridge import MpiPromptBridge
from .prompt_gen.prompt_override import (
    MpiPromptOverride,
    MpiPromptOverrideSeed,
)
from .prompt_gen.display_prompts import MpiDisplayPrompt
from .prompt_gen.rand_prompt_gen import (
    MpiRandPromptGenOrder,
    MpiRandPromptGenOverrideSection,
    MpiRandPromptGenOverrideList,
    MpiRandPromptGen,
    MpiRandPromptGenSave,
)
from .batch_text_replace import MpiBatchTextReplace
from .add_image_to_list import MpiAddImageToList
from .logger import MpiLogger, MpiExecLogger
from .img import (
    MpiBboxToMask,
    MpiScaledDimensions,
    MpiAspectRatio,
    MpiGetImageAtIndex,
    MpiMaskDebugInfo,
    MpiGridDimensions,
    MpiUpscaleModelScale,
    MpiLoadImageFromPath,
    MpiCrop,
    MpiMaskSquareBbox,
    MpiBox,
    MpiFromBox,
    MpiBoxCrop,
    MpiBoxMask,
    MpiInpaintHeal,
)
from .text_list_replace import MpiTextListReplace
from .text_list_join import MpiTextListJoin
from .normalize_value import MpiNormalizeValue
from .logic import (
    MpiRoundToMultiple,
    MpiRoundToMultipleRes,
    MpiCompare,
    MpiConvert,
    MpiBoolean,
    MpiSimpleBoolean,
    MpiBooleanCompare,
    MpiBooleanInvert,
    MpiFloat,
    MpiInt,
    MpiString,
    MpiText,
    MpiListCount,
    MpiListRange,
    MpiTextContains,
    MpiReroute,
    MpiAnyBlocker,
    MpiBlocker,
    MpiIsListEmpty,
    MpiBlockIfEmptyList,
    MpiAnyChecker,
    MpiSeedPassthrough,
    MpiConditioningReroute,
)
from .math import MpiMath, MpiExpoFloat, MpiClamp
from .switches import (
    MpiStringInvSwitch,
    MpiAnyInvSwitch,
    MpiLoraSwitch,
    MpiAnySwitch,
    MpiAnySwitch10,
    MpiPacker,
    MpiUnpacker,
    MpiPacker10,
    MpiUnpacker10,
    MpiComparePacks,
)
from .loras import (
    MpiDoubleLora,
    MpiLoraModel,
    MpiLoraModelClip,
    MpiStyleSelector,
    MpiStyleLoras,
)
from .json import MpiJsonLoad, MpiJsonSave
from .if_else import (
    MpiIfElse,
    MpiIfElseInverted,
    MpiIfElseProbability,
    MpiIfElseProbabilityInverted,
)
from .checkpoint import MpiFromCheckpoint, MpiToChekPoint
from .multi_text import (
    MpiMultiTextX2,
    MpiMultiTextX3,
    MpiMultiTextX4,
    MpiMultiTextX5,
)
from .wan import MpiWanFrames, MpiWanSeconds
from .h3 import MpiH3EncodeAV, MpiH3Length, MpiH3MaskedPrefix, MpiH3References
from .vram import MpiClearVram
from .video import MpiHasAudio, MpiSaveVideo, MpiLoadVideo, MpiLoadAudio
from .latent import MpiSaveLatent, MpiLoadLatent, MpiStageLatents, MpiLatentUpscale
from .preview import MpiVideoSamplingPreview, MpiTinyVaeLoader
from .splat import MpiBrushTrain

# TEST NODES
# from .dynamic_combo import MpiDynamicCombo
# from .test_dummy import MpiDummyToggleNode
# from .subgraph_test import MpiSubGraphTest


NODE_CLASS_MAPPINGS = {
    "MpiBatchTextReplace": MpiBatchTextReplace,
    "MpiBboxToMask": MpiBboxToMask,
    "MpiAddImageToList": MpiAddImageToList,
    "MpiLogger": MpiLogger,
    "MpiExecLogger": MpiExecLogger,
    "MpiScaledDimensions": MpiScaledDimensions,
    "MpiTextListReplace": MpiTextListReplace,
    "MpiTextListJoin": MpiTextListJoin,
    "MpiPromptList": MpiPromptList,
    "MpiPromptListSelector": MpiPromptListSelector,
    "MpiPromptProcessor": MpiPromptProcessor,
    "MpiNormalizeValue": MpiNormalizeValue,
    "MpiExpoFloat": MpiExpoFloat,
    "MpiPromptChainSelector": MpiPromptChainSelector,
    "MpiPromptListJoin": MpiPromptListJoin,
    "MpiRoundToMultiple": MpiRoundToMultiple,
    "MpiRoundToMultipleRes": MpiRoundToMultipleRes,
    "MpiCompare": MpiCompare,
    "MpiConvert": MpiConvert,
    "MpiMath": MpiMath,
    "MpiClamp": MpiClamp,
    "MpiBoolean": MpiBoolean,
    "MpiSimpleBoolean": MpiSimpleBoolean,
    "MpiBooleanCompare": MpiBooleanCompare,
    "MpiBooleanInvert": MpiBooleanInvert,
    "MpiFloat": MpiFloat,
    "MpiInt": MpiInt,
    "MpiString": MpiString,
    "MpiText": MpiText,
    "MpiListCount": MpiListCount,
    "MpiListRange": MpiListRange,
    "MpiTextContains": MpiTextContains,
    "MpiReroute": MpiReroute,
    "MpiAnyBlocker": MpiAnyBlocker,
    "MpiBlockIfEmpty": MpiAnyBlocker,  # alias: keeps pre-rename saved workflows loading
    "MpiBlocker": MpiBlocker,
    "MpiIsListEmpty": MpiIsListEmpty,
    "MpiBlockIfEmptyList": MpiBlockIfEmptyList,
    "MpiAnyChecker": MpiAnyChecker,
    "MpiSeedPassthrough": MpiSeedPassthrough,
    "MpiConditioningReroute": MpiConditioningReroute,
    "MpiDisplayPrompt": MpiDisplayPrompt,
    "MpiHasOptions": MpiHasOptions,
    "MpiPromptBridge": MpiPromptBridge,
    "MpiPromptBridge": MpiPromptBridge,
    "MpiStringInvSwitch": MpiStringInvSwitch,
    "MpiAnyInvSwitch": MpiAnyInvSwitch,
    "MpiLoraSwitch": MpiLoraSwitch,
    "MpiAnySwitch": MpiAnySwitch,
    "MpiAnySwitch10": MpiAnySwitch10,
    "MpiPacker": MpiPacker,
    "MpiUnpacker": MpiUnpacker,
    "MpiPacker10": MpiPacker10,
    "MpiUnpacker10": MpiUnpacker10,
    "MpiComparePacks": MpiComparePacks,
    "MpiDoubleLora": MpiDoubleLora,
    "MpiLoraModel": MpiLoraModel,
    "MpiLoraModelClip": MpiLoraModelClip,
    "MpiStyleSelector": MpiStyleSelector,
    "MpiStyleLoras": MpiStyleLoras,
    "MpiAspectRatio": MpiAspectRatio,
    "MpiGetImageAtIndex": MpiGetImageAtIndex,
    "MpiUpscaleModelScale": MpiUpscaleModelScale,
    "MpiLoadImageFromPath": MpiLoadImageFromPath,
    "MpiCrop": MpiCrop,
    "MpiMaskSquareBbox": MpiMaskSquareBbox,
    "MpiBox": MpiBox,
    "MpiFromBox": MpiFromBox,
    "MpiBoxCrop": MpiBoxCrop,
    "MpiBoxMask": MpiBoxMask,
    "MpiInpaintHeal": MpiInpaintHeal,
    "MpiPromptOverride": MpiPromptOverride,
    "MpiPromptOverrideSeed": MpiPromptOverrideSeed,
    "MpiJsonLoad": MpiJsonLoad,
    "MpiJsonSave": MpiJsonSave,
    "MpiRandPromptGenOrder": MpiRandPromptGenOrder,
    "MpiRandPromptGenOverrideSection": MpiRandPromptGenOverrideSection,
    "MpiRandPromptGenOverrideList": MpiRandPromptGenOverrideList,
    "MpiRandPromptGenSave": MpiRandPromptGenSave,
    "MpiRandPromptGen": MpiRandPromptGen,
    "MpiIfElse": MpiIfElse,
    "MpiIfElseInverted": MpiIfElseInverted,
    "MpiIfElseProbability": MpiIfElseProbability,
    "MpiIfElseProbabilityInverted": MpiIfElseProbabilityInverted,
    "MpiFromCheckpoint": MpiFromCheckpoint,
    "MpiToChekPoint": MpiToChekPoint,
    "MpiMultiTextX2": MpiMultiTextX2,
    "MpiMultiTextX3": MpiMultiTextX3,
    "MpiMultiTextX4": MpiMultiTextX4,
    "MpiMultiTextX5": MpiMultiTextX5,
    "MpiMaskDebugInfo": MpiMaskDebugInfo,
    "MpiGridDimensions": MpiGridDimensions,
    "MpiWanFrames": MpiWanFrames,
    "MpiWanSeconds": MpiWanSeconds,
    "MpiH3EncodeAV": MpiH3EncodeAV,
    "MpiH3Length": MpiH3Length,
    "MpiH3MaskedPrefix": MpiH3MaskedPrefix,
    "MpiH3References": MpiH3References,
    "MpiClearVram": MpiClearVram,
    "MpiHasAudio": MpiHasAudio,
    "MpiSaveVideo": MpiSaveVideo,
    "MpiLoadVideo": MpiLoadVideo,
    "MpiLoadAudio": MpiLoadAudio,
    "MpiSaveLatent": MpiSaveLatent,
    "MpiLoadLatent": MpiLoadLatent,
    "MpiStageLatents": MpiStageLatents,
    "MpiLatentUpscale": MpiLatentUpscale,
    "MpiVideoSamplingPreview": MpiVideoSamplingPreview,
    "MpiTinyVaeLoader": MpiTinyVaeLoader,
    "MpiBrushTrain": MpiBrushTrain,
    # TESTS
    # "MpiDummyToggleNode": MpiDummyToggleNode,
    # "MpiDynamicCombo": MpiDynamicCombo,
    # "MpiSubGraphTest": MpiSubGraphTest,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "MpiBatchTextReplace": "Mpi Batch Text Replace",
    "MpiBboxToMask": "Mpi Bbox To Mask",
    "MpiAddImageToList": "Mpi Add Image to List",
    "MpiLogger": "Mpi Logger",
    "MpiExecLogger": "Mpi Exec Logger",
    "MpiScaledDimensions": "Mpi Scaled Dimensions",
    "MpiTextListReplace": "Mpi Text List Replace",
    "MpiTextListJoin": "Mpi Text List Join",
    "MpiPromptList": "Mpi Prompt List",
    "MpiPromptListSelector": "Mpi Prompt List Selector",
    "MpiPromptProcessor": "Mpi Prompt Processor",
    "MpiNormalizeValue": "Mpi Normalize Value",
    "MpiExpoFloat": "Mpi Expo Float",
    "MpiPromptChainSelector": "Mpi Prompt Chain Selector",
    "MpiPromptListJoin": "Mpi Prompt List Join",
    "MpiRoundToMultiple": "Mpi Round To Multiple",
    "MpiRoundToMultipleRes": "Mpi Round To Multiple Res",
    "MpiCompare": "Mpi Compare",
    "MpiConvert": "Mpi Convert",
    "MpiMath": "Mpi Math",
    "MpiClamp": "Mpi Clamp",
    "MpiBoolean": "Mpi Boolean",
    "MpiSimpleBoolean": "Mpi Simple Bool",
    "MpiBooleanCompare": "Mpi Boolean Compare",
    "MpiBooleanInvert": "Mpi Boolean Invert",
    "MpiFloat": "Mpi Float",
    "MpiInt": "Mpi Int",
    "MpiString": "Mpi String",
    "MpiText": "Mpi Text",
    "MpiListCount": "Mpi List Count",
    "MpiListRange": "Mpi List Range",
    "MpiTextContains": "Mpi Text Contains",
    "MpiReroute": "Mpi Reroute",
    "MpiAnyBlocker": "Mpi Any Blocker",
    "MpiBlockIfEmpty": "Mpi Any Blocker",
    "MpiBlocker": "Mpi Blocker",
    "MpiIsListEmpty": "Mpi Is List Empty",
    "MpiBlockIfEmptyList": "Mpi Block If Empty List",
    "MpiAnyChecker": "Mpi Any Checker",
    "MpiSeedPassthrough": "Mpi Seed Passthrough",
    "MpiConditioningReroute": "Mpi Conditioning Reroute",
    "MpiDisplayPrompt": "Mpi Prompt Display",
    "MpiHasOptions": "Mpi Has Options",
    "MpiPromptBridge": "Mpi Prompt Bridge",
    "MpiLoraSwitch": "Mpi Lora Switch",
    "MpiAnySwitch": "Mpi Any Switch",
    "MpiAnySwitch10": "Mpi Any Switch 10",
    "MpiStringInvSwitch": "Mpi String Inverted Switch",
    "MpiAnyInvSwitch": "Mpi Any Inverted Switch",
    "MpiPacker": "Mpi Packer",
    "MpiUnpacker": "Mpi Unpacker",
    "MpiPacker10": "Mpi Packer 10",
    "MpiUnpacker10": "Mpi Unpacker 10",
    "MpiComparePacks": "Mpi Compare Packs",
    "MpiDoubleLora": "Mpi Double Lora Loader",
    "MpiLoraModel": "Mpi Lora Model",
    "MpiLoraModelClip": "Mpi Lora Model Clip",
    "MpiStyleSelector": "Mpi Style Selector",
    "MpiStyleLoras": "Mpi Style Loras",
    "MpiAspectRatio": "Mpi Get Aspect Ratio",
    "MpiGetImageAtIndex": "Mpi Get Image At Index",
    "MpiUpscaleModelScale": "Mpi Upscale Model Scale",
    "MpiLoadImageFromPath": "Mpi Load Image From Path",
    "MpiCrop": "Mpi Crop",
    "MpiMaskSquareBbox": "Mpi Mask Square Bbox",
    "MpiBox": "Mpi Box",
    "MpiFromBox": "Mpi From Box",
    "MpiBoxCrop": "Mpi Box Crop",
    "MpiBoxMask": "Mpi Box Mask",
    "MpiInpaintHeal": "Mpi Inpaint Heal",
    "MpiGridDimensions": "Mpi Grid Dimensions",
    "MpiPromptOverride": "Mpi Prompt Override",
    "MpiPromptOverrideSeed": "Mpi Prompt Override Seed",
    "MpiJsonLoad": "Mpi Json Load",
    "MpiJsonSave": "Mpi Json Save",
    "MpiRandPromptGen": "Mpi RandPromptGen",
    "MpiRandPromptGenSave": "Mpi RandPromptGen Save",
    "MpiRandPromptGenOrder": "Mpi RandPromptGen Order",
    "MpiRandPromptGenOverrideSection": "Mpi RandPromptGen Override Section",
    "MpiRandPromptGenOverrideList": "Mpi RandPromptGen Override List",
    "MpiIfElse": "Mpi If Else",
    "MpiIfElseProbability": "Mpi If Else Probability",
    "MpiIfElseProbabilityInverted": "Mpi If Else Probability Inverted",
    "MpiIfElseInverted": "Mpi If Else Inverted",
    "MpiFromCheckpoint": "Mpi From Checkpoint",
    "MpiToChekPoint": "Mpi To ChekPoint",
    "MpiMultiTextX2": "Mpi Multi Text x2",
    "MpiMultiTextX3": "Mpi Multi Text x3",
    "MpiMultiTextX4": "Mpi Multi Text x4",
    "MpiMultiTextX5": "Mpi Multi Text x5",
    "MpiMaskDebugInfo": "Mpi Mask Debug Info",
    "MpiWanFrames": "Mpi Wan Frames",
    "MpiWanSeconds": "Mpi Wan Seconds",
    "MpiH3EncodeAV": "Mpi H3 Encode AV",
    "MpiH3Length": "Mpi H3 Length",
    "MpiH3MaskedPrefix": "Mpi H3 Masked Prefix",
    "MpiH3References": "Mpi H3 References",
    "MpiClearVram": "Mpi Clear Vram",
    "MpiHasAudio": "Mpi Has Audio",
    "MpiSaveVideo": "Mpi Save Video",
    "MpiLoadVideo": "Mpi Load Video",
    "MpiLoadAudio": "Mpi Load Audio",
    "MpiSaveLatent": "Mpi Save Latent",
    "MpiLoadLatent": "Mpi Load Latent",
    "MpiStageLatents": "Mpi Stage Latents",
    "MpiLatentUpscale": "Mpi Latent Upscale",
    "MpiVideoSamplingPreview": "Mpi Video Sampling Preview",
    "MpiTinyVaeLoader": "Mpi Tiny Vae Loader",
    "MpiBrushTrain": "Mpi Brush Train",
}

WEB_DIRECTORY = "./web"

# Server routes (not workflow nodes) — importing registers them on PromptServer
# at startup. See routes.py: POST /mpi/reload-extra-paths (Cubric Vision MPI-219).
from . import routes  # noqa: E402,F401

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
